application: klauspost-talks
version: talks-test
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /static
  static_dir: present/static
  application_readable: true
- url: /.*
  script: _go_app

nobuild_files: ^201[0-9]/
